### ISSUE TITLE
Provide deb package for quick download

### ISSUE THREAD

**Issue by MurzNN** [obiwankennedy/HotShots#1]
Thanks for continue developing so useful HotShots app and  porting to KDE 5.x / Qt5. Will be good to have pre-compiled deb packages for quick install on Debian / Ubuntu systems, or PPA with same packages.

**Comment by obiwankennedy** [comment]
https://launchpad.net/~rolisteam/+archive/ubuntu/rolisteamdev/+sourcepub/8792720/+listing-archive-extra

**Comment by MurzNN** [comment]
Thanks, installed successfully on Ubuntu 17.10 and works well!

**Comment by obiwankennedy** [comment]
Please, keep it mind that I had to remove some piece of code to make it compile with Qt5. So be cautious when you use it. Save your work often.
