### ISSUE TITLE
Global printscreen shortcut not working

### ISSUE THREAD

**Issue by b4dpxl** [obiwankennedy/HotShots#16]
I am running Fedora 33 with KDE, and have set the printscreen button to be my "capture region" shortcut. But this only works when hotshots' interface is in focus. I have selected "use system screen capture shortcuts". With the original (QT4?) version, this worked on Fedora 31. The default screen capture (spectacle) is disabled.

I could create a custom shortcut, if I knew what trigger to use. Is there a command I can call to trigger a screen capture? Or a DBUS trigger?

Thanks

**Comment by obiwankennedy** [comment]
I don't plan to make improvement on HotShots. 
I needed a software once to screenshot my own opensource  application and I take time to make it works on Qt5, but I commented out many line of code. 
Now Flameshot, Shutter and peek are the application I use.

A random dude, share my repo on reddit or something and now everyone thinks that i'm the new dev. 
Some people had fork my repo perhaps one of them is planning to keep developping on it.

**Comment by b4dpxl** [comment]
Fair enough. You might want to archive this repo then, or at least disable issues if you're not planning on supporting it. I've tried flameshot and shutter, and neither of them met my specific requirements, but hotshots did :shrug:
