### ISSUE TITLE
compile failure

### ISSUE THREAD

**Issue by sliptonic** [obiwankennedy/HotShots#5]
I really like Hotshots and it's become an essential part of my workflow.  Please keep on with it.  As far as I know, it's the only screenshot tool that lets me repeat the last screen selection.  this essential for making documentation look consistent. 

I recently upgraded to Linux Mint 19.  I tried building with qmake -recursive HotShots.pro  and get the following error.  

g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtMultimedia -I/usr/include/qt4 -Isrc/3rdparty/qkeysequencewidget -Isrc/3rdparty/QSgml -Isrc/3rdparty/wwWidgets -Isrc/3rdparty/qt-json -Isrc/3rdparty/qxt -Isrc/uploaders -Isrc/editor -Isrc/editor/items -Isrc/editor/widgets -Isrc/editor/io -Isrc -I/usr/include/qxt/QxtGui -I/usr/include/qxt/QxtCore -I/usr/include/QxtGui -I/usr/include/QxtCore -I/usr/local/Qxt/include/QxtGui -I/usr/local/Qxt/include/QxtCore -Irelease -Irelease -o release/GroupLayer.o src/editor/GroupLayer.cpp
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtMultimedia -I/usr/include/qt4 -Isrc/3rdparty/qkeysequencewidget -Isrc/3rdparty/QSgml -Isrc/3rdparty/wwWidgets -Isrc/3rdparty/qt-json -Isrc/3rdparty/qxt -Isrc/uploaders -Isrc/editor -Isrc/editor/items -Isrc/editor/widgets -Isrc/editor/io -Isrc -I/usr/include/qxt/QxtGui -I/usr/include/qxt/QxtCore -I/usr/include/QxtGui -I/usr/include/QxtCore -I/usr/local/Qxt/include/QxtGui -I/usr/local/Qxt/include/QxtCore -Irelease -Irelease -o release/EditorWidget.o src/editor/EditorWidget.cpp
src/editor/EditorWidget.cpp:36:10: fatal error: QStandardPaths: No such file or directory
 #include <QStandardPaths>
          ^~~~~~~~~~~~~~~~
compilation terminated.
Makefile.Release:910: recipe for target 'release/EditorWidget.o' failed
make[1]: *** [release/EditorWidget.o] Error 1
make[1]: Leaving directory '/home/brad/HotShots'
Makefile:34: recipe for target 'release' failed
make: *** [release] Error 2

**Comment by obiwankennedy** [comment]
hi, You are compiling with Qt4. I made the change to support Qt5 and only Qt5. 

> -I/usr/share/**qt4**/

**Comment by sliptonic** [comment]
Thanks.  A little closer.  I have QT5 installed now.  If I run qmake-=r HotShots.pro from the build directory, it fails with 
/usr/lib/qt5/bin/rcc: File does not exist 'res/hotshots.qrc'

If I run it from the top level, it returns without error but make fails like this:
brad@hairball:~/HotShots$ make
make -f Makefile.Release
make[1]: Entering directory '/home/brad/HotShots'
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -Isrc/3rdparty/qkeysequencewidget -Isrc/3rdparty/QSgml -Isrc/3rdparty/wwWidgets -Isrc/3rdparty/qt-json -Isrc/3rdparty/qxt -Isrc/uploaders -Isrc/editor -Isrc/editor/items -Isrc/editor/widgets -Isrc/editor/io -Isrc -isystem /usr/include/qxt/QxtGui -isystem /usr/include/qxt/QxtCore -isystem /usr/include/QxtGui -isystem /usr/include/QxtCore -I/usr/local/Qxt/include/QxtGui -I/usr/local/Qxt/include/QxtCore -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtMultimedia -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Irelease -isystem /usr/include/libdrm -Irelease -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o release/EditorWidget.o src/editor/EditorWidget.cpp
In file included from src/editor/EditorWidget.cpp:42:0:
release/ui_EditorWidget.h:13:10: fatal error: QtGui/QAction: No such file or directory
 #include <QtGui/QAction>
          ^~~~~~~~~~~~~~~
compilation terminated.
Makefile.Release:1335: recipe for target 'release/EditorWidget.o' failed
make[1]: *** [release/EditorWidget.o] Error 1
make[1]: Leaving directory '/home/brad/HotShots'
Makefile:40: recipe for target 'release' failed
make: *** [release] Error 2

**Comment by obiwankennedy** [comment]
The code is generated. It may be result from the previous compilation with Qt4. You should clean up the directory. 
I just push commit to fix compilation issue with Ubuntu 18.04 compiler and Qt5.11. It should work.

**Comment by sliptonic** [comment]
Hmm.  No luck.  I fetched your last commit and reset --hard to origin/master so the tree is identical. 
I still get the same error on make.  qt version is 5.9.5 in mint 19

**Comment by sliptonic** [comment]
More progress:

I did:
qmake -r HotShot.pro
make clean
make
The compile looks to have completed correctly but sudo make install does nothing
make[1]: Nothing to be done for 'install'.
All this done from the top level of the tree, not the build directory

**Comment by obiwankennedy** [comment]
if you run `uic --version`, what's the output ?

**Comment by sliptonic** [comment]
5.9.5  

BTW launching the binary from the release directory works!  Just need the install now.  Thanks.

**Comment by obiwankennedy** [comment]
OK good news. I did not put any install rules. I will do so, this weekend as it looks important to you.

**Comment by obiwankennedy** [comment]
I added  installation rules in the qmake file. It should work now.

**Comment by sliptonic** [comment]
confirmed.  Thank you.  One note.  The INSTALL.txt file says to do the qmake/make from the build directory.  This didn't work for me.  I had to do it from the parent.  You might want to revise the instructions.
