### ISSUE TITLE
Consider a Flatpak port to keep this software in the public domain.

### ISSUE THREAD

**Issue by Just-Another-Gnumer** [obiwankennedy/HotShots#6]
By custom I am making a request to port Hotshots to Flathub. Flathub is a service for universal binary compatible Linux apps. This will insure that Hotshots will be around for years to come and others will have the same benefit from this software as I did. I would hate for this software to be lost to history, as it is vital to my workflow. So if you are interested in porting it let us know. Thank you so much for rebuilding it in QT5.

![image](https://user-images.githubusercontent.com/78667207/109460317-48155380-7a58-11eb-9021-b90ceef3dff8.png)

**Comment by Just-Another-Gnumer** [comment]
I filed a request with the flatpak team as recommended. 

https://discourse.flathub.org/t/hotshots-high-quality-qt5-screenshot-annotator-for-flathub/1149

**Comment by Just-Another-Gnumer** [comment]
Update, a flatpak was created and it appears to work as intended.

https://github.com/fastrizwaan/HotShots_flatpak

This topic is finished  and will not be continued unless a bug is found.

**Comment by obiwankennedy** [comment]
Thank a lot!
